### ISSUE TITLE
Installing HCS takes forever

### ISSUE THREAD

**Issue by HanZel62** [MaxvandeLaar/homey-community-store-installer#29]
taking a while is for more than an hour now. whats wrong?

grtz  Hans

![1 hour now](https://user-images.githubusercontent.com/67095531/126351372-8850adc3-23e7-4e58-9a66-b59856fa018d.JPG)

**Comment by MaxvandeLaar** [comment]
@HanZel62, an hour is definitely way too long. It is always hard to diagnose the issue without having any logs, however, this is not the first time I hear this. 

It most likely is caused by Homey reporting it was offline in the CLI. A simple solution would be to run `homey logout` in your terminal. After that run the installer again (it will ask you to login) and it will most likely work. If you don't have the Homey development  environment set up please follow this guide first https://apps.developer.homey.app/the-basics/getting-started

If you need help, let me know.

**Comment by HanZel62** [comment]
Tried the cli installer but failed again due to permissions. Homey however did ask for some updates. After that the installation program did run smouthly. Problem solved.Thnx.Grtz. HansVerzonden vanaf mijn Galaxy
-------- Oorspronkelijk bericht --------Van: Max ***@***.***> Datum: 21-07-2021  09:15  (GMT+01:00) Aan: MaxvandeLaar/homey-community-store-installer ***@***.***> Cc: HanZel62 ***@***.***>, Mention ***@***.***> Onderwerp: Re: [MaxvandeLaar/homey-community-store-installer] Installing HCS takes forever (#29) 
@HanZel62, an hour is definitely way too long. It is always hard to diagnose the issue without having any logs, however, this is not the first time I hear this.
It most likely is caused by Homey reporting it was offline in the CLI. A simple solution would be to run homey logout in your terminal. After that run the installer again (it will ask you to login) and it will most likely work. If you don't have the Homey development  environment set up please follow this guide first https://apps.developer.homey.app/the-basics/getting-started
If you need help, let me know.
